seed: 111
env_init_seed: 1
eval_init_seed: 2

num_train_steps: 50000
num_envs: 16

agent:
  learning_rate: 3e-4
  baseline_learning_rate: 1e-4
  baseline_num_splits: 2
  baseline_num_epochs: 4
  gae_lambda: 0.7

network:
  # Input size and output size are computed based on the environment
  hidden_size: 256
  depth: 2

metrics:
  n_rounds : 10
  batch_size: 1024

logging:
  track_each: 100 # in terms of total training steps, not divided by num_envs
  eval_each: 500 # in terms of total training steps, not divided by num_envs
  metric_buffer_size: 200000
  tqdm_print_rate: 20
  use_writer: false
  log_dir: null # If null, dir will be automatically created
  checkpoint_dir: null # If null, dir will be automatically created

# Technical information for writer
writer:
  writer_type: null # wandb, trackio, comet_ml or null (no logging online)
  save_locally: false # Save metrics locally or not
  entity: null
  project: null
  offline_directory: ./comet_offline_logs # Used only for comet_ml when COMET_OFFLINE=1 env variable is set

# Technical information for hydra
hydra:
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}